config:
subcomponents:
  istio:
    config:
      grafana:
        enabled: true
      tracing:
        enabled: true
      prometheus:
        enabled: true
  istio-azure-monitor:
    config:
      instrumentation:
        logLevel: Trace
        applicationInsightsKey: "my-application-insights-key"
        watchingNamespaces: "default,bookinfo,istio-system,kube-system"
